### ISSUE TITLE
Not working in Windows 11 22H2

### ISSUE THREAD

**Issue by RebelliousX** [Arakula/vstdriver#4]
It doesn't work after Windows 11 feature update .

**Comment by Falcosoft** [comment]
Would you try this fork?
https://github.com/Falcosoft/vstdriver
It should have no problem with Win 11.

**Comment by RebelliousX** [comment]
@Falcosoft Thanks for mentioning this, and thank you for working on this.

~~Unfortunately, it still doesn't work with Windows 11, I have 23H2 now. I uninstalled all coolsoftmidi, loopmidi..etc. I started clean, installed vstmididrv v2.1.0, loaded S-YXG50.dll. And I tried to play some midi files, the sound is still the same as if I didn't install vstmididrv. I tried installing ASIO4ALL and change playback output, nothing.~~

~~I hit configure for the vst plugin to see the equalizer for Syxg50 vst plugin, and no response to the music playback.~~

~~I guess I gotta go back to my old solution, loopmidi and savihost :(~~

Edit: I noticed there are 2 VST Midi ports created when I tried the midi input plugin in Winamp! I tried again, but this time, I installed coolsoft midi mapper, and chose VST port A. ... and it works 👍🏻 This should be mentioned in the `Readme.md` in your fork imho.

**Comment by Falcosoft** [comment]
Hi,
1. Since Windows 8 you cannot change default system-wide Midi Out port without 3rd party software (Coolsoft Midi Mapper).
I assumed this was a well known fact since it happened relatively a long time ago (more than 10 years). 
So yes, If you would like to use a software that cannot select a Midi Out port explicitly but always uses the default port you need Coolsot Midi Mapper. 
But otherwise in a Midi software that can select Midi Out ports explicitly VST Midi Driver port A/B can work without Coolsoft Midi Mapper installed. 
2. The Configuration dialog is only for configuration. At config time you open a VST dialog version that is totally independent from the driver. Actually the configuration part is an independent project/application that works even without the driver component installed. Its only purpose is to save settings to registry/.set file that the driver loads when it is opened by a Midi client.
So there is no point in opening the config utility when the driver is active since it will not reflect the running state of the driver.
That's why there is the new option "Show VST dialog when a port is activated". The actual state of the driver is reflected in this dialog (which is completely independent from the config time dialog).

**Comment by RebelliousX** [comment]
@Falcosoft more than likely I was wrong, but it has been a few years since I used vstmididrv successfully, last time it was during Windows 10, probably in 2018-2019. But in Windows 10 it was working, and I remember it stopped working after Win11 22H2. I don't remember it was creating 2 midi ports, since I was creating them manually using loopmidi and I used savihost and Syxg50 vsti plugin with that.

But anyways, thanks a million, your updated version is working. When I was using loopMidi and savihost, I always had problems playing Shell Shock by Sam Sketty midi music file, it always worked the first time, playing another midi xg file and trying to play Shell Shock again caused weird noisy instruments and timings gets jumbled. But now, with your updated version of vstmididrv everything is ok 😁

I am starring your repo to keep looking for future updates 👍
